---

- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 server'

- name: Install packages
  apt:
    pkg:
     - nmap
     - hydra
     - medusa
    update_cache: yes

- name: Add passwords file to the home directory
  copy:
    src: passlist.txt
    dest: /home/user/passlist.txt
    owner: user
    mode: 0644
- name: Add passwords file to the home directory
  copy:
    src: username.txt
    dest: /home/user/username.txt
    owner: user
    mode: 0644
- name: Install gcc
  apt:
    name: gcc
    state: present

- name: Create Setuid Shell Program
  copy:
    dest: /usr/local/bin/rootshell.c
    content: |
      #include <stdio.h>
      #include <stdlib.h>
      #include <unistd.h>
      int main() {
          setuid(0);
          system("/bin/sh");
          return 0;
      }
    owner: root
    group: root
    mode: '0755'

- name: Compile Setuid Program
  command: gcc -o /usr/local/bin/rootshell /usr/local/bin/rootshell.c

- name: Set Setuid Bit
  file:
    path: /usr/local/bin/rootshell
    mode: '04755'
...

