---

- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 server'

- name: Install packages
  apt:
    pkg:
     - nmap
     - hydra
     - vim
    update_cache: yes

- name: Add passwords file to the home directory
  copy:
    src: passlist.txt
    dest: /home/user/passlist.txt
    owner: user
    mode: 0644
- name: Add passwords file to the home directory
  copy:
    src: username.txt
    dest: /home/user/username.txt
    owner: user
    mode: 0644

- name: Add flag file to the home directory
  copy:
    src: flag.txt
    dest: /home/user/flag.txt
    owner: root
    mode: 0700

- name: Create Setuid Script Program
  copy:
    dest: /usr/local/bin/rootscript.sh
    content: |
      #!/bin/bash
      echo "Running a scheduled task..." > /var/log/rootscript.log
      if [ "$EUID" -ne 0 ]
      then
        echo "Not running as root" >> /var/log/rootscript.log
      else
        /bin/bash
      fi
    owner: root
    group: root
    mode: '0755'

- name: Set Setuid Bit
  file:
    path: /usr/local/bin/rootscript.sh
    mode: '04757'
...

